# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 409)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 601, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton3 = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.radioButton3.setObjectName("radioButton3")
        self.gridLayout.addWidget(self.radioButton3, 2, 1, 1, 1)
        self.radioButton2 = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.radioButton2.setObjectName("radioButton2")
        self.gridLayout.addWidget(self.radioButton2, 1, 1, 1, 1)
        self.radioButton1 = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.radioButton1.setObjectName("radioButton1")
        self.gridLayout.addWidget(self.radioButton1, 0, 1, 1, 1)
        self.zmienButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.zmienButton.setObjectName("zmienButton")
        self.gridLayout.addWidget(self.zmienButton, 3, 1, 1, 1)
        self.wpisanie = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.wpisanie.setObjectName("wpisanie")
        self.gridLayout.addWidget(self.wpisanie, 0, 0, 2, 1)
        self.wynik = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.wynik.setObjectName("wynik")
        self.gridLayout.addWidget(self.wynik, 2, 0, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton3.setText(_translate("Dialog", "odwrotnie"))
        self.radioButton2.setText(_translate("Dialog", "duze"))
        self.radioButton1.setText(_translate("Dialog", "male"))
        self.zmienButton.setText(_translate("Dialog", "zmien"))
